/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-661"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151204"
#define PACKAGE_DATE_STRING "04 Dec 15"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "661"
#define REV_BINARY_SHA "0e17312fe5ad8e399d83f6c8c1a3c14c8b294c5c87367b772dc84da022950976"
#define GIT_BRANCH "titles/fantavision"
#define GIT_REV_DATE "20151204-2"
#define GIT_HASH_BINARY "39284d3a9b972c1dfa8d7b43382e6b0ad1ec0f0d"
#define GIT_DESCRIPTION "dist-829-361-g39284d3"

