/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1195"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161018"
#define PACKAGE_DATE_STRING "18 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1195"
#define REV_BINARY_SHA "71329463559dadd51f1ba8ffe708ccb888d51e4ad9b02b9fb39e45a8d5ce9c4c"
#define GIT_BRANCH "titles/SamuraiShodown6"
#define GIT_REV_DATE "20161018-5"
#define GIT_HASH_BINARY "32e571b564d3e785024a349d01e88d01a94bf6ea"

