/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1378"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170120"
#define PACKAGE_DATE_STRING "25 Jan 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1378"
#define REV_BINARY_SHA "721fdf8fb28355d9b6865cc4c8d884735670a60420cf92621942b952030636e9"
#define GIT_BRANCH "titles/EternalRing"
#define GIT_REV_DATE "20170120-6"
#define GIT_HASH_BINARY "ada1105cc8bf5f02c14e9daa99ba4109d35472ae"

