/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1631"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20171114"
#define PACKAGE_DATE_STRING "14 Nov 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1631"
#define REV_BINARY_SHA "ef9560ed3babae3f80a756d2426a9021d645201c309bae031a445bf32459dce0"
#define GIT_BRANCH "titles/Jak123X"
#define GIT_REV_DATE "20171114-0"
#define GIT_HASH_BINARY "fc81f9634914c8358c5317f0a12b16f6542f0ec8"

