/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1244"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1244"
#define REV_BINARY_SHA "469ca2fb6a370f3dfd4be3f9724336fdf8916931aa77b571eaa960ef20cf1762"
#define GIT_BRANCH "titles/wotm-WarOfTheMonsters"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "a5666829d2bafa42e14c7ed609be910441af0ec8"
#define GIT_DESCRIPTION "dist-829-231-ga566682"

