/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-764"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151222"
#define PACKAGE_DATE_STRING "26 Jan 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "764"
#define REV_BINARY_SHA "ff1d4338153e882a06799a2cc63437637e45679b6bd52021f5e0630d85021c7f"
#define GIT_BRANCH "titles/PuzzleQuestCotW"
#define GIT_REV_DATE "20151222-1"
#define GIT_HASH_BINARY "77e7f417c5cafcd8f917957e731ebc83e18fefc2"
#define GIT_DESCRIPTION "dist-829-603-g77e7f41"

