/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1273"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "27 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1273"
#define REV_BINARY_SHA "9318d60bdd13c72784323398abf2822a1841572f8a0e26218cae9d5ece74c355"
#define GIT_BRANCH "titles/gta-ViceCity"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "3af0c9e5b656a0c17be3c1500f4efa12d20863fb"

