/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging-1309"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160921"
#define PACKAGE_DATE_STRING "08 Nov 16"
#define JENKINS_JOB_NAME "Packaging"
#define JENKINS_JOB_NUMBER "1309"
#define REV_BINARY_SHA "2d4d812b44262b564c462588ed5272af67f92fbe7895ba30e929f0c07f002297"
#define GIT_BRANCH "titles/ParappaTheRapper2"
#define GIT_REV_DATE "20160921-2"
#define GIT_HASH_BINARY "a07db4ba6dbcd54aa5a2ce97ab41a0bf1eff2a2f"
#define GIT_DESCRIPTION "dist-829-305-ga07db4b"

