/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1265"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1265"
#define REV_BINARY_SHA "dd03268d8016037d245d5260cf90e737081a3a0c406db27239e6dfbbb2493179"
#define GIT_BRANCH "titles/TheWarriors"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "bd9c071d5193cc62200007297ad77cd28be0b391"

