/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-533"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151020"
#define PACKAGE_DATE_STRING "20 Oct 15"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "533"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20151020-3"
#define GIT_HASH_BINARY "bb83647d775ece68164f1f30a88b0289de332f4a"
#define GIT_DESCRIPTION "dist-829-682-gbb83647"

