/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1707"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20180314"
#define PACKAGE_DATE_STRING "27 Apr 18"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1707"
#define REV_BINARY_SHA "217ebf741851533c1b8f8685b83f86f81e72c923d57e176bcd286965fc728f87"
#define GIT_BRANCH "titles/JakX-CombatRacing"
#define GIT_REV_DATE "20180314-0"
#define GIT_HASH_BINARY "65731d94c2174227a7c74f0b579df4f0d1d25567"

