/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1296"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "04 Nov 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1296"
#define REV_BINARY_SHA "805a10844c5224ac3973bee54469b03468f4779aa0aeba52230d1ced1cc5007b"
#define GIT_BRANCH "titles/Psychonauts"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "211d45938507d1fd4af40d79ce45457848bb0de3"

