/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1253"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1253"
#define REV_BINARY_SHA "e0571fe52ca2ad58bc0bc7b74a3ac2ccd094ee592d678d227d73dca46d4940d2"
#define GIT_BRANCH "titles/StarWarsBountyHunter"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "4593bc1081e55d3ad2855a93283ec771fff94152"
#define GIT_DESCRIPTION "dist-829-533-g4593bc1"

