/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1238"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "24 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1238"
#define REV_BINARY_SHA "35148b27637a129f98e06f0f8101bc4addf51f0ee64240d453ff6c8e9ca405f7"
#define GIT_BRANCH "titles/RiseOfTheKasai"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "6fdc4f58dd5737a80f01be61b1feda87d9d8ed20"

