/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1247"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1247"
#define REV_BINARY_SHA "97ca384c35d03f76065757851379da31312d65bd3cead5a3088b31134f36b86c"
#define GIT_BRANCH "titles/Fantavision"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "3d07039cb0fa7fcd428e761dce00d002a8581e46"
#define GIT_DESCRIPTION "dist-829-374-g3d07039"

