/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1499"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170405"
#define PACKAGE_DATE_STRING "07 Apr 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1499"
#define REV_BINARY_SHA "93f4408cfcebb798bd7f3f761c9cdebe9aedb7ee958ab1490cd152d1201280ef"
#define GIT_BRANCH "titles/ResidentEvilCodeVeronicaX"
#define GIT_REV_DATE "20170405-7"
#define GIT_HASH_BINARY "ec3b24319af5277b4622be50148ced62a8bdad5f"

