/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-952"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160420"
#define PACKAGE_DATE_STRING "21 Apr 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "952"
#define REV_BINARY_SHA "27ca31b514e087eee2c9d95ea7e22e9ab33dd37723f129d7ecd21752d2ec2d13"
#define GIT_BRANCH "titles/TheWarriors"
#define GIT_REV_DATE "20160420-1"
#define GIT_HASH_BINARY "8bcce73537e3adcd2c6de2c2d8bd958941689501"

