/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1252"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1252"
#define REV_BINARY_SHA "99423b908e42d94a164a2c8ea02dde32f70241580c7985b07278e4948a0e9ff4"
#define GIT_BRANCH "titles/DarkCloud"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "8cdae0bde6bd025bb0836acfebadc4d70ec3db46"

