/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-667"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151201"
#define PACKAGE_DATE_STRING "09 Dec 15"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "667"
#define REV_BINARY_SHA "235cd48f3c074f34c86990a0ab3760b6ffda6091a4c0af1a161fd3b5a499a427"
#define GIT_BRANCH "titles/ArcTheLad-TotS"
#define GIT_REV_DATE "20151201-1"
#define GIT_HASH_BINARY "62469257f5106e1748b9c2717029a141436c84a3"
#define GIT_DESCRIPTION "titles/ArcTheLad-TotS-A0100-V0100-14-g6246925"

