/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1599"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170825"
#define PACKAGE_DATE_STRING "28 Aug 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1599"
#define REV_BINARY_SHA "93f4408cfcebb798bd7f3f761c9cdebe9aedb7ee958ab1490cd152d1201280ef"
#define GIT_BRANCH "titles/Jak1-TPL"
#define GIT_REV_DATE "20170825-4"
#define GIT_HASH_BINARY "1d4879dbbe0f923cb97f5bbf6dc130aeb4e84d7c"

