/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1062"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160615"
#define PACKAGE_DATE_STRING "22 Jul 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1062"
#define REV_BINARY_SHA "7ed72025a2efd1f91c7f14fe7eb5ce40995a96107d4d8d6f7a496aeb930982e9"
#define GIT_BRANCH "titles/KOF2000"
#define GIT_REV_DATE "20160615-1"
#define GIT_HASH_BINARY "8d591ac76b726f33d6ec74c2b26d989d9a6ade7b"

