/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging-648"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151126"
#define PACKAGE_DATE_STRING "26 Nov 15"
#define JENKINS_JOB_NAME "Packaging"
#define JENKINS_JOB_NUMBER "648"
#define REV_BINARY_SHA "206c8c00d14c19001e3042bf9e3d95c1ade0b89f380b55138f7273e24b072b4e"
#define GIT_BRANCH "titles/ParappaTheRapper2"
#define GIT_REV_DATE "20151126-8"
#define GIT_HASH_BINARY "01c55b53cdcb9f65461034f6ce834bb14d5e5524"
#define GIT_DESCRIPTION "dist-829-289-g01c55b5"

