/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1632"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20171115"
#define PACKAGE_DATE_STRING "15 Nov 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1632"
#define REV_BINARY_SHA "ef9560ed3babae3f80a756d2426a9021d645201c309bae031a445bf32459dce0"
#define GIT_BRANCH "titles/JakX-CombatRacing"
#define GIT_REV_DATE "20171115-0"
#define GIT_HASH_BINARY "b92faf8bb7d752bb7efb7f8182132b9eb3830dfa"

