/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-953"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160412"
#define PACKAGE_DATE_STRING "21 Apr 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "953"
#define REV_BINARY_SHA "568debaa40dd0be5143fa5aa7627335beb6670e17c86996110fde47e3aa26b02"
#define GIT_BRANCH "titles/Kinetica"
#define GIT_REV_DATE "20160412-1"
#define GIT_HASH_BINARY "35590090b2984e0eec14694c3f1b1eceebb9326c"

