/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1295"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "04 Nov 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1295"
#define REV_BINARY_SHA "6b0641f12a6960ed896a9c3c7579447fff04a3d440c026b5d47e84a02fa228f4"
#define GIT_BRANCH "titles/WildArms3"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "c0a7481d9862a290ce76e507e4f5b59783b6386e"
#define GIT_DESCRIPTION "dist-829-441-gc0a7481"

