/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1054"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160708"
#define PACKAGE_DATE_STRING "08 Jul 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1054"
#define REV_BINARY_SHA "425c70bc978f8525d62569131949f8224a839c79e3be405d9026fa687e2cda0b"
#define GIT_BRANCH "titles/ApeEscape2"
#define GIT_REV_DATE "20160708-4"
#define GIT_HASH_BINARY "6837b6d68f7136772ac4129c30d62f979c6ee080"

