/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1254"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1254"
#define REV_BINARY_SHA "ec9349e5abb8023dd7e8398958468803f3b5eba94c7edf698fb5d17f9df1e631"
#define GIT_BRANCH "titles/StarWarsJediStarfighter"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "8cde175c70ba2c4d2de8ae6843911543bd65a98c"
#define GIT_DESCRIPTION "dist-829-729-g8cde175"

