/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Package-Test-437"
#define PACKAGE_BUILT_BY "rottikunta"
#define PACKAGE_BUILT_ON "20150827"
#define PACKAGE_DATE_STRING "11 Sep 15"
#define JENKINS_JOB_NAME "Package-Test"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20150827-1"
#define GIT_HASH_SHORT "0c904a9311a6"
#define GIT_HASH_FULL "0c904a9311a60f8edb407c0624db0a1f4a2b64f9"
#define ISD_HASH_SHORT "b5818bf5489d"
#define ISD_HASH_FULL "b5818bf5489dec18ccc621f7e75c0704395add3a"
#define GIT_DESCRIPTION "dist-829-269-g0c904a9"

