/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging-1024"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160601"
#define PACKAGE_DATE_STRING "03 Jun 16"
#define JENKINS_JOB_NAME "Packaging"
#define JENKINS_JOB_NUMBER "1024"
#define REV_BINARY_SHA "686b18787aa8f518f2c472ae6eadf94ef28a645b818841fee503c71251138b26"
#define GIT_BRANCH "titles/Siren"
#define GIT_REV_DATE "20160601-1"
#define GIT_HASH_BINARY "6ea5a548430b72397314f84e79a1a2caef0302f0"
#define GIT_DESCRIPTION "dist-829-308-g6ea5a54"

