/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-977"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160502"
#define PACKAGE_DATE_STRING "03 May 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "977"
#define REV_BINARY_SHA "d5ffb6079e2b4aaf32307b6a0b52c224e4fd81b5e240193c041bde94acabd260"
#define GIT_BRANCH "titles/Primal"
#define GIT_REV_DATE "20160502-2"
#define GIT_HASH_BINARY "b552abacbfa6f7e708996da24f37fbf1a9c8de41"

