/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1239"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "24 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1239"
#define REV_BINARY_SHA "3380374f617a41d647eeeb6bd70f338623fa621c8967dc9b6b4ebcea292adbfe"
#define GIT_BRANCH "titles/StarWarsRacerRevenge"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "1c5b2e064ea6ddb1c6951b87028bf268135de42b"
#define GIT_DESCRIPTION "dist-829-636-g1c5b2e0"

