/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1145"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160823"
#define PACKAGE_DATE_STRING "28 Sep 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1145"
#define REV_BINARY_SHA "f0207aa1d909063aafd9f78007159a47ad7236081df57cdc41b45df2c0475d03"
#define GIT_BRANCH "titles/DestroyAllHumans"
#define GIT_REV_DATE "20160823-3"
#define GIT_HASH_BINARY "2d0220b8b7d468a466c7e17d1029a82158454381"

