/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1081"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160823"
#define PACKAGE_DATE_STRING "23 Aug 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1081"
#define REV_BINARY_SHA "552dfde873f073c3b5820b9d02e1c604ba89a91b26bb3c22d3599fc8a69212e9"
#define GIT_BRANCH "titles/HotShotsTennis"
#define GIT_REV_DATE "20160823-3"
#define GIT_HASH_BINARY "f20f25c4b7f0bdda271f9a5794cf4f2c801a9215"

