/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-540"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20151009"
#define PACKAGE_DATE_STRING "21 Oct 15"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "540"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20151009-1"
#define GIT_HASH_BINARY "01967274aea5b7e3f3e2a000b024a23d730a5f65"
#define GIT_DESCRIPTION "dist-829-584-g0196727"

