/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1441"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170224"
#define PACKAGE_DATE_STRING "07 Mar 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1441"
#define REV_BINARY_SHA "93f4408cfcebb798bd7f3f761c9cdebe9aedb7ee958ab1490cd152d1201280ef"
#define GIT_BRANCH "titles/FatalFuryBattleArchivesVol2"
#define GIT_REV_DATE "20170224-3"
#define GIT_HASH_BINARY "34c09df6647c94c7770efac35d95a6b8bac87134"

