/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1560"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170421"
#define PACKAGE_DATE_STRING "05 Jul 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1560"
#define REV_BINARY_SHA "4f4ebbec76dbcf710cc877ef099a57782c1628ca707996e518dba3b9d19c377f"
#define GIT_BRANCH "titles/ArtOfFightingAnthology"
#define GIT_REV_DATE "20170421-1"
#define GIT_HASH_BINARY "10addf8f2f34e2d293c58611cb1029e51ec4955c"

