/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1297"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161011"
#define PACKAGE_DATE_STRING "04 Nov 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1297"
#define REV_BINARY_SHA "f0207aa1d909063aafd9f78007159a47ad7236081df57cdc41b45df2c0475d03"
#define GIT_BRANCH "titles/DestroyAllHumans2"
#define GIT_REV_DATE "20161011-1"
#define GIT_HASH_BINARY "5bda63a10da0ea6ca0b660edfafa2ba3bf4cde9b"

