/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-882"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160218"
#define PACKAGE_DATE_STRING "15 Mar 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "882"
#define REV_BINARY_SHA "8816ce8eca9810aba82949804b6e52a8bca8239cc35c15d0bee83b1eee491679"
#define GIT_BRANCH "titles/Bully"
#define GIT_REV_DATE "20160218-2"
#define GIT_HASH_BINARY "68cc2486fdd789319d7ae349bf4f1736c83ab1a6"

