/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1564"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170627"
#define PACKAGE_DATE_STRING "14 Jul 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1564"
#define REV_BINARY_SHA "4f4ebbec76dbcf710cc877ef099a57782c1628ca707996e518dba3b9d19c377f"
#define GIT_BRANCH "titles/RedFaction2"
#define GIT_REV_DATE "20170627-1"
#define GIT_HASH_BINARY "54ba12a40012380ec3a0887f30b51c5c91044c66"

