/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1241"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1241"
#define REV_BINARY_SHA "b5fe8551653975cdfe1434f0ebbcbcb68614dfbc25a01ae0c4f908c047436838"
#define GIT_BRANCH "titles/OkageShadowKing"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "6cf07c83a1c9c0825a2eff1df17bd456977eac62"

