/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1263"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161027"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1263"
#define REV_BINARY_SHA "7683a536ae4fc7779ebe96a00588a4c82fc10468bbdbb17bd562208d4d957406"
#define GIT_BRANCH "titles/MaxPayne1"
#define GIT_REV_DATE "20161027-1"
#define GIT_HASH_BINARY "5b7c909b9a5d1238361b733eb6f06cc1aefa6483"

