/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1249"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1249"
#define REV_BINARY_SHA "d556de4341872de849cfb24aa3b0704c419282ffc79e01918674193582e886ff"
#define GIT_BRANCH "titles/mark-of-kri"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "c7d3dd27c48dc7a867a6de2b5276e11f0102ca43"
#define GIT_DESCRIPTION "titles/mark-of-kri-A0100-V0100-39-gc7d3dd2"

