/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1061"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160713"
#define PACKAGE_DATE_STRING "22 Jul 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1061"
#define REV_BINARY_SHA "3f3358a5c9d3aa97155d4487fa6e8c5f18f9cee75cbb0d46b96c24c9ece59dba"
#define GIT_BRANCH "titles/IndigoProphecy"
#define GIT_REV_DATE "20160713-1"
#define GIT_HASH_BINARY "94a1784d58851837bf9b128269694f9a440f929b"

