/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1264"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161027"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1264"
#define REV_BINARY_SHA "270278742a92317b035c94650104a112f37e64cd266cc84ddeafbc70aee54ac9"
#define GIT_BRANCH "titles/Bully"
#define GIT_REV_DATE "20161027-1"
#define GIT_HASH_BINARY "5cccb76349c053837cd8ff2e151a450fe1732dce"

