/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1243"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1243"
#define REV_BINARY_SHA "19d390b85c3fff6796c0e0603b6f8747f8f7f5c802c2c7aad9f6deda910b076e"
#define GIT_BRANCH "titles/Kinetica"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "b676bfc5f7d615d178ac26bc629ec2254a466719"

