/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1513"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170426"
#define PACKAGE_DATE_STRING "26 Apr 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1513"
#define REV_BINARY_SHA "471587412b7f6e972c0deb70f24de8d88db3ba03db5b174551d8fc30ad535670"
#define GIT_BRANCH "titles/StarOcean3"
#define GIT_REV_DATE "20170426-6"
#define GIT_HASH_BINARY "0b685f66ef8e31beccb0562fda3e62415ec4247b"

