/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1627"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20171109"
#define PACKAGE_DATE_STRING "09 Nov 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1627"
#define REV_BINARY_SHA "ef9560ed3babae3f80a756d2426a9021d645201c309bae031a445bf32459dce0"
#define GIT_BRANCH "titles/Jak123X"
#define GIT_REV_DATE "20171109-0"
#define GIT_HASH_BINARY "96511e89bc38e1ee454b2d9cf6d33c7c674e7904"

