/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1548"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170421"
#define PACKAGE_DATE_STRING "01 Jun 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1548"
#define REV_BINARY_SHA "21643912815af42dc7cc2719f0a3e4bbc5372e21f51bf97ee90dd60ca2cf3584"
#define GIT_BRANCH "titles/EternalRing"
#define GIT_REV_DATE "20170421-1"
#define GIT_HASH_BINARY "2576fe80c57a580deae07f56903b236dfd576d69"

