/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1396"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170207"
#define PACKAGE_DATE_STRING "07 Feb 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1396"
#define REV_BINARY_SHA "ad83c29db842395274316d0bd175d3112b47ab25e0ed9715df94fc5c7e81bfc7"
#define GIT_BRANCH "titles/ADKDamashii"
#define GIT_REV_DATE "20170207-1"
#define GIT_HASH_BINARY "245bb2b4741fff22e15aad0476d77f20e30d38a0"

