/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1679"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20171121"
#define PACKAGE_DATE_STRING "08 Jan 18"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1679"
#define REV_BINARY_SHA "4f4ebbec76dbcf710cc877ef099a57782c1628ca707996e518dba3b9d19c377f"
#define GIT_BRANCH "titles/kof-KingOfFighters98"
#define GIT_REV_DATE "20171121-5"
#define GIT_HASH_BINARY "c3344dccc8a0a0a96f2f1f9e44e116abbd48387c"

