/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1251"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1251"
#define REV_BINARY_SHA "bedfddc7b2754cb7a03637bbb10192b72ff1b371527d657b5b56a80f150810c9"
#define GIT_BRANCH "titles/DarkCloud2"
#define GIT_REV_DATE "20161024-4"
#define GIT_HASH_BINARY "0c0c6d8fb31813db81c244a94fafc27764c9aa97"
#define GIT_DESCRIPTION "dist-829-406-g0c0c6d8"

