/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1035"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160615"
#define PACKAGE_DATE_STRING "21 Jun 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1035"
#define REV_BINARY_SHA "3c2020ecde7c793ccf72bed055014c4b4ae86cb2f84b88f72404f20d69d7eeca"
#define GIT_BRANCH "titles/MetalSlugAnthology"
#define GIT_REV_DATE "20160615-1"
#define GIT_HASH_BINARY "045d6547f733ee0e269faf31c9818fa4d7dd625b"

