/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-939"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160409"
#define PACKAGE_DATE_STRING "13 Apr 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "939"
#define REV_BINARY_SHA "571ee071b4c751a0c50bd837bb2f311ac6dd56da1ff70d9aefbd8c51bd350ed3"
#define GIT_BRANCH "titles/Psychonauts"
#define GIT_REV_DATE "20160409-5"
#define GIT_HASH_BINARY "e0030f2a652e27761c8410fb8fb68abaf9c2939a"

