/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-905"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160318"
#define PACKAGE_DATE_STRING "30 Mar 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "905"
#define REV_BINARY_SHA "7fe4f4af3df8aaf864435459539f9f2f45ae8d78e3b7c067e9635cdcce24e8f8"
#define GIT_BRANCH "titles/MaxPayne1"
#define GIT_REV_DATE "20160318-2"
#define GIT_HASH_BINARY "52abb5d0b8c47f1ad03ea9196f7a387e285d0e76"

