/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Package-Test-439"
#define PACKAGE_BUILT_BY "rottikunta"
#define PACKAGE_BUILT_ON "20150911"
#define PACKAGE_DATE_STRING "11 Sep 15"
#define JENKINS_JOB_NAME "Package-Test"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20150911-15"
#define GIT_HASH_SHORT "679ddde9142e"
#define GIT_HASH_FULL "679ddde9142e71d3c85650de1ffcbae8dba41d90"
#define ISD_HASH_SHORT "b5818bf5489d"
#define ISD_HASH_FULL "b5818bf5489dec18ccc621f7e75c0704395add3a"
#define GIT_DESCRIPTION "dist-829-284-g679ddde"

