/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1501"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20170407"
#define PACKAGE_DATE_STRING "10 Apr 17"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1501"
#define REV_BINARY_SHA "93f4408cfcebb798bd7f3f761c9cdebe9aedb7ee958ab1490cd152d1201280ef"
#define GIT_BRANCH "titles/kof-KingOfFightersCollection"
#define GIT_REV_DATE "20170407-8"
#define GIT_HASH_BINARY "4dcc23242c44abb41098536e8e0aaeed6665fab5"

