/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1245"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "25 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1245"
#define REV_BINARY_SHA "9e511b20ea41e8dbc0657b9aafa663a9536fea9f7354ac0913d6b2fa61546d70"
#define GIT_BRANCH "titles/tmb-TwistedMetalBlack"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "a41ca29e02bf1ea14042a9b9ca08188feedd03af"

