/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-789"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160203"
#define PACKAGE_DATE_STRING "04 Feb 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "789"
#define REV_BINARY_SHA "d4e3ddd0daf7051fe2c877489945150466e064ee6145215c9c2c346377f6465c"
#define GIT_BRANCH "stable"
#define GIT_REV_DATE "20160203-4"
#define GIT_HASH_BINARY "110f30c72d396ffe7cf6a0f60cc578afc0af7be4"

