/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1678"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20171129"
#define PACKAGE_DATE_STRING "08 Jan 18"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1678"
#define REV_BINARY_SHA "4f4ebbec76dbcf710cc877ef099a57782c1628ca707996e518dba3b9d19c377f"
#define GIT_BRANCH "titles/kof-KingOfFightersCollection"
#define GIT_REV_DATE "20171129-8"
#define GIT_HASH_BINARY "7a5ce188bd541c54b50f09abde80101a9dd69b02"

