/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Package-Test-421"
#define PACKAGE_BUILT_BY "rottikunta"
#define PACKAGE_BUILT_ON "20150827"
#define PACKAGE_DATE_STRING "31 Aug 15"
#define JENKINS_JOB_NAME "Package-Test"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20150827-3"
#define GIT_HASH_SHORT "15b671ce4755"
#define GIT_HASH_FULL "15b671ce47558a83973f268c3ad3186db9a07e4f"
#define ISD_HASH_SHORT "b883567980a6"
#define ISD_HASH_FULL "b883567980a67b1c1ded012e9fe2e37691b75f1c"
#define GIT_DESCRIPTION "dist-829-196-g15b671c"

