/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1261"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161024"
#define PACKAGE_DATE_STRING "26 Oct 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1261"
#define REV_BINARY_SHA "8fe47565919986577ebf8a5ed037bd704e4081da7dd054df03c5d64f56152e91"
#define GIT_BRANCH "titles/Manhunt"
#define GIT_REV_DATE "20161024-1"
#define GIT_HASH_BINARY "9229bf21a56f422fb9335e7dd079bbefb6aa9e81"

