/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1308"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20161101"
#define PACKAGE_DATE_STRING "08 Nov 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1308"
#define REV_BINARY_SHA "cca96ed0142cc5a621a5fc66d7688bc3668c8f05b1ae64ff83b5d9d88e499289"
#define GIT_BRANCH "titles/RedFaction"
#define GIT_REV_DATE "20161101-1"
#define GIT_HASH_BINARY "6b434ef3a5352f4b20349d8495a3e3e214461151"

