/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-1023"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160601"
#define PACKAGE_DATE_STRING "03 Jun 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "1023"
#define REV_BINARY_SHA "8025a26e98128cf8b12c54055fe2d02aab82c86ff47481d9153216ecc2547427"
#define GIT_BRANCH "titles/gta-SanAndreas"
#define GIT_REV_DATE "20160601-1"
#define GIT_HASH_BINARY "4691c7d4db07b6e9f93e5ce55c8a77ff26a5a4a4"

