/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Package-Test-422"
#define PACKAGE_BUILT_BY "rottikunta"
#define PACKAGE_BUILT_ON "20150827"
#define PACKAGE_DATE_STRING "01 Sep 15"
#define JENKINS_JOB_NAME "Package-Test"
#define GIT_BRANCH "olympack/master"
#define GIT_REV_DATE "20150827-3"
#define GIT_HASH_SHORT "15b671ce4755"
#define GIT_HASH_FULL "15b671ce47558a83973f268c3ad3186db9a07e4f"
#define ISD_HASH_SHORT "6d4d301f562e"
#define ISD_HASH_FULL "6d4d301f562e157a138b78a2cc3db43bb7bcd4c9"
#define GIT_DESCRIPTION "dist-829-196-g15b671c"

