/* This file is autogenerated. DO NOT EDIT. */
#define PACKAGE_NAME "Packaging/PackageBuild-BuildBinary-855"
#define PACKAGE_BUILT_BY ""
#define PACKAGE_BUILT_ON "20160302"
#define PACKAGE_DATE_STRING "02 Mar 16"
#define JENKINS_JOB_NAME "Packaging/PackageBuild-BuildBinary"
#define JENKINS_JOB_NUMBER "855"
#define REV_BINARY_SHA "e7b5332c2bc9283245f9e9387aed8833f962830daf759bf4c0d4fcc89ba5aef9"
#define GIT_BRANCH "titles/OkageShadowKing"
#define GIT_REV_DATE "20160302-6"
#define GIT_HASH_BINARY "937a375047fd6e78530e1a2a64803c70ed73d8d6"

